In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train=pd.read_csv('/home/vinay/Downloads/HDFC_ML/DataSet/Train.csv')
test=pd.read_csv('/home/vinay/Downloads/HDFC_ML/DataSet/Test.csv')

/home/vinay/anaconda3/envs/tensor/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (746,835) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/home/vinay/anaconda3/envs/tensor/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (700,731,740,752,761,789,811,820,829,841,850) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17521 entries, 0 to 17520
Columns: 2395 entries, Col1 to Col2397
dtypes: float64(844), int64(1548), object(3)
memory usage: 320.2+ MB


In [4]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20442 entries, 0 to 20441
Columns: 2394 entries, Col1 to Col2397
dtypes: float64(837), int64(1545), object(12)
memory usage: 373.4+ MB


In [5]:
test.shape

(20442, 2394)

In [6]:
train.shape

(17521, 2395)

In [7]:
trainobjects = train.select_dtypes(include=[object])
print(trainobjects.columns)

Index(['Col1', 'Col747', 'Col836'], dtype='object')


In [8]:
testobjects = test.select_dtypes(include=[object])
print(testobjects.columns)

Index(['Col1', 'Col702', 'Col733', 'Col742', 'Col754', 'Col763', 'Col791',
       'Col813', 'Col822', 'Col831', 'Col843', 'Col852'],
      dtype='object')


In [9]:
rcolumns=trainobjects+testobjects
print(rcolumns.columns)

Index(['Col1', 'Col702', 'Col733', 'Col742', 'Col747', 'Col754', 'Col763',
       'Col791', 'Col813', 'Col822', 'Col831', 'Col836', 'Col843', 'Col852'],
      dtype='object')


In [10]:
print(rcolumns.shape)

(20442, 14)


In [11]:
y=train['Col2']

In [12]:
train=train.drop(columns=rcolumns.columns)
train.drop('Col2', axis=1, inplace=True)
print(train.shape)

(17521, 2380)


In [13]:
x=train

In [14]:
x.fillna(0, inplace=True)

In [15]:
nan_cols = [i for i in x.columns if x[i].isnull().any()]
print(len(nan_cols))

0


In [16]:
y.isnull().sum()

0

In [17]:
print(x.shape,y.shape)

(17521, 2380) (17521,)


In [18]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3) # 70% training and 30% test

In [19]:
zero=one=0
for val in y_test:
    if val==0:
        zero+=1
    else:
        one+=1
print("Zeros  :",zero)
print("Ones   :",one)

Zeros  : 4742
Ones   : 515


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'n_estimators': [90,100,150,200]}
#Create a Gaussian Classifier
clf=RandomForestClassifier()
rf_clf=GridSearchCV(clf,param_grid)
rf_clf.fit(x_train, y_train)
print(rf_clf.best_params_)
print(rf_clf.best_score_)
y_pred=rf_clf.predict(x_test)

In [31]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
#Train the model using the training sets y_pred=clf.predict(X_test)
from sklearn.metrics import precision_recall_fscore_support
print(precision_recall_fscore_support(y_test,y_pred,average='macro'))
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.8997527106714857
(0.7069506268632335, 0.5202954689632634, 0.5152274089336255, None)
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      4729
           1       0.51      0.05      0.08       528

    accuracy                           0.90      5257
   macro avg       0.71      0.52      0.52      5257
weighted avg       0.86      0.90      0.86      5257

[[4706   23]
 [ 504   24]]


In [20]:
test.shape

(20442, 2394)

In [21]:
test.Col1

0        RIGD58ZWD
1        RIH660YDS
2        RIH660Q96
3        RIYDO15W1
4        RIYBGC1ZD
           ...    
20437     OL0I6O5R
20438     OL0I65ZW
20439     OL0I6CXW
20440       O2VIUO
20441     M7VKV5QD
Name: Col1, Length: 20442, dtype: object

In [22]:
testid=test['Col1']
print(testid.head())

0    RIGD58ZWD
1    RIH660YDS
2    RIH660Q96
3    RIYDO15W1
4    RIYBGC1ZD
Name: Col1, dtype: object


In [23]:
test=test.drop(columns=rcolumns.columns)


In [24]:
print(test.shape)

(20442, 2380)


In [25]:
test.fillna(0, inplace=True)
nan_cols = [i for i in test.columns if test[i].isnull().any()]
print(len(nan_cols))

0


In [37]:
result=clf.predict(test)


NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [ ]:
zero=one=0
for val in result:
    if val==0:
        zero+=1
    else:
        one+=1
print("Zeros  :",zero)
print("Ones   :",one)

In [ ]:
predictions=np.asarray([testid,result])
predictions=predictions.T

In [ ]:
pd.DataFrame(predictions,columns=['Col1','Col2']).to_csv("/home/vinay/Downloads/HDFC_ML/DataSet/Predictions.csv")

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid = {'n_neighbors': [10,50,100,200,300]}
knn = KNeighborsClassifier()
knn_cv = GridSearchCV(knn, param_grid)
knn_cv.fit(x_train, y_train)
print(knn_cv.best_params_)
print(knn_cv.best_score_)
y_pred=clf.predict(x_test)
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
result=clf.predict(test)
predictions=np.asarray([testid,result])
predictions=predictions.T
pd.DataFrame(predictions,columns=['Col1','Col2']).to_csv("/home/vinay/Downloads/HDFC_ML/DataSet/Predictionsknn.csv")

In [33]:
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
xclas = XGBClassifier()  # and for classifier  
i=1111
for train_index, test_index in sss.split(x, y):
    x_train, x_test = x.iloc[train_index], x.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    xclas.fit(x_train, y_train)  
    y_pred=xclas.predict(x_test)
    print("Accuracy "+str(i)+":",metrics.accuracy_score(y_test, y_pred))
    result=xclas.predict(test)
    print(precision_recall_fscore_support(y_test,y_pred,average='macro'))
    print(classification_report(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    predictions=np.asarray([testid,result])
    predictions=predictions.T
    pd.DataFrame(predictions,columns=['Col1','Col2']).to_csv("/home/vinay/Downloads/HDFC_ML/DataSet/Predictionsxgsss"+str(i)+".csv")
    i+=1

Accuracy 1111: 0.8990014265335236
(0.6886736599213639, 0.5223965991984546, 0.5194166860330003, None)
              precision    recall  f1-score   support

           0       0.90      0.99      0.95      3153
           1       0.47      0.05      0.09       352

    accuracy                           0.90      3505
   macro avg       0.69      0.52      0.52      3505
weighted avg       0.86      0.90      0.86      3505

[[3133   20]
 [ 334   18]]
Accuracy 1112: 0.9009985734664765
(0.7558125015608221, 0.5184591514574863, 0.5111841245918111, None)
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      3153
           1       0.61      0.04      0.07       352

    accuracy                           0.90      3505
   macro avg       0.76      0.52      0.51      3505
weighted avg       0.87      0.90      0.86      3505

[[3144    9]
 [ 338   14]]
Accuracy 1113: 0.9001426533523538
(0.7183213429256594, 0.5205071648934637, 0.5154816785523

In [ ]:
result=clf.predict(test)
predictions=np.asarray([testid,result])
predictions=predictions.T

#pd.DataFrame(predictions,columns=['Col1','Col2']).to_csv("/home/vinay/Downloads/HDFC_ML/DataSet/Predictionsxg.csv")

In [ ]:
#from xgboost.sklearn import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y,test_size=0.25)
xclas = AdaBoostClassifier()  # and for classifier  
xclas.fit(x_train, y_train)  
y_pred=xclas.predict(x_test)
print("Accuracy :",metrics.accuracy_score(y_test, y_pred))
result=clf.predict(test)
predictions=np.asarray([testid,result])
predictions=predictions.T
print(predictions[:5])
#pd.DataFrame(predictions,columns=['Col1','Col2']).to_csv("/home/vinay/Downloads/HDFC_ML/DataSet/Predictionsxgsss.csv")

In [29]:
from sklearn.metrics import precision_recall_fscore_support
print(precision_recall_fscore_support(y_test,y_pred,average='macro'))
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

(0.7069506268632335, 0.5202954689632634, 0.5152274089336255, None)
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      4729
           1       0.51      0.05      0.08       528

    accuracy                           0.90      5257
   macro avg       0.71      0.52      0.52      5257
weighted avg       0.86      0.90      0.86      5257

[[4706   23]
 [ 504   24]]


In [34]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

cv = cross_val_score(clf, x, y, cv=5)